use kestrel_proto::derive_per_node_psk;
use rand::RngCore;
use zeroize::Zeroizing;

/// Generate a 32-byte hub master secret. Per-node PSKs are HKDF-derived
/// from this on every connect; the master itself never leaves the hub
/// keyring. Wrapped in `Zeroizing` so the underlying bytes get wiped
/// when the binding goes out of scope.
pub fn generate_master_secret() -> Zeroizing<Vec<u8>> {
    let mut key = Zeroizing::new(vec![0u8; 32]);
    rand::thread_rng().fill_bytes(&mut key);
    key
}

/// Print-ready agent enrollment line for a specific node. The hub-side
/// master_secret is HKDF-expanded into a per-node PSK; only that derived
/// PSK is given to the agent, so a leaked agent key cannot derive any
/// other node's key or the master.
pub fn enrollment_command(hub_ip: &str, node_id: &str, master_secret: &[u8]) -> String {
    let psk = derive_per_node_psk(master_secret, node_id);
    format!(
        "kestrel-agent enroll --hub {} --node-id {} --key {}",
        hub_ip,
        node_id,
        hex::encode(psk)
    )
}

pub fn store_master_secret(master_secret: &[u8]) -> anyhow::Result<()> {
    let entry = keyring::Entry::new("kestrel", "master_secret")?;
    entry.set_password(&hex::encode(master_secret))?;
    Ok(())
}

/// Load the hub master secret from the system keyring, wrapped in
/// `Zeroizing` so it gets wiped from memory when the returned binding
/// drops. The intermediate hex string isn't zeroized — it's already
/// passed through `keyring::Entry::get_password` which returns a `String`
/// we don't control — so this is best-effort defense-in-depth, not a
/// guarantee.
pub fn load_master_secret() -> anyhow::Result<Zeroizing<Vec<u8>>> {
    let entry = keyring::Entry::new("kestrel", "master_secret")?;
    Ok(Zeroizing::new(hex::decode(entry.get_password()?)?))
}

/// 32 random bytes hex-encoded — used as a Bearer token on the hub's mutation
/// endpoints (POST/DELETE /api/nodes). Generated by `kestrel-hub init` and
/// loaded by the CLI's add-node/remove-node from the same keyring entry.
pub fn generate_control_token() -> String {
    let mut bytes = [0u8; 32];
    rand::thread_rng().fill_bytes(&mut bytes);
    hex::encode(bytes)
}

pub fn store_control_token(token: &str) -> anyhow::Result<()> {
    let entry = keyring::Entry::new("kestrel", "control_token")?;
    entry.set_password(token)?;
    Ok(())
}

pub fn load_control_token() -> anyhow::Result<String> {
    let entry = keyring::Entry::new("kestrel", "control_token")?;
    Ok(entry.get_password()?)
}

/// Result of a single unenroll step. Errors are non-fatal — unenroll proceeds
/// best-effort across all keyring entries and reports per-step.
#[derive(Debug)]
pub enum UnenrollStep {
    Cleared(&'static str),
    NotFound(&'static str),
    Failed(&'static str, String),
}

impl UnenrollStep {
    pub fn label(&self) -> &'static str {
        match self {
            UnenrollStep::Cleared(_) => "cleared",
            UnenrollStep::NotFound(_) => "not found",
            UnenrollStep::Failed(_, _) => "failed",
        }
    }
    pub fn what(&self) -> &'static str {
        match self {
            UnenrollStep::Cleared(w) | UnenrollStep::NotFound(w) | UnenrollStep::Failed(w, _) => w,
        }
    }
}

fn clear_keyring_entry(service: &str, account: &'static str) -> UnenrollStep {
    match keyring::Entry::new(service, account) {
        Ok(entry) => match entry.delete_password() {
            Ok(()) => UnenrollStep::Cleared(account),
            Err(keyring::Error::NoEntry) => UnenrollStep::NotFound(account),
            Err(e) => UnenrollStep::Failed(account, e.to_string()),
        },
        Err(e) => UnenrollStep::Failed(account, e.to_string()),
    }
}

/// Clear hub-side secrets from the system credential store. Returns one
/// `UnenrollStep` per keyring entry so the caller can report per-step status.
///
/// `psk` is included for legacy cleanup: pre-per-node-PSK installs stored a
/// fleet-wide PSK under that account name. New installs use `master_secret`
/// only — the legacy entry being NotFound is expected and reported as such.
pub fn clear_hub_keyring() -> Vec<UnenrollStep> {
    vec![
        clear_keyring_entry("kestrel", "master_secret"),
        clear_keyring_entry("kestrel", "psk"), // legacy
        clear_keyring_entry("kestrel", "control_token"),
    ]
}

/// Write a starter hub kestrel.toml at `path`. Refuses to overwrite if a file
/// already exists at that path.
pub fn scaffold_hub_config(path: &str, dashboard_addr: &str) -> anyhow::Result<()> {
    if std::path::Path::new(path).exists() {
        anyhow::bail!("{} already exists", path);
    }
    let contents = format!(
        r#"# Kestrel hub configuration. Edit by hand or use `kestrel-hub` subcommands
# (add-node, remove-node, layout-set, layout-unset) to mutate it programmatically.

[hub]
listen_mcp       = "stdio"
listen_dashboard = "{dashboard_addr}"

# Nodes the hub connects to. Add with `kestrel-hub add-node <id> <addr>`.

# Optional KVM layout for cursor-edge routing. Add with `kestrel-hub layout-set <id> <col> <row>`.
"#,
        dashboard_addr = dashboard_addr,
    );
    std::fs::write(path, contents)
        .map_err(|e| anyhow::anyhow!("write {}: {}", path, e))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_master_secret_is_32_bytes() {
        let key = generate_master_secret();
        assert_eq!(key.len(), 32);
    }

    #[test]
    fn enrollment_command_contains_required_parts() {
        let master = vec![0u8; 32];
        let cmd = enrollment_command("192.168.1.10", "alpha", &master);
        assert!(cmd.contains("kestrel-agent enroll"));
        assert!(cmd.contains("192.168.1.10"));
        assert!(cmd.contains("--node-id alpha"));
        assert!(cmd.contains("--key"));
    }

    #[test]
    fn enrollment_command_prints_derived_not_master() {
        // The per-node PSK printed in the enrollment line MUST be the HKDF
        // derivation, not the master itself — otherwise leaking the line
        // leaks the master.
        let master = vec![0xABu8; 32];
        let cmd = enrollment_command("10.0.0.1", "alpha", &master);
        let derived = kestrel_proto::derive_per_node_psk(&master, "alpha");
        assert!(cmd.contains(&hex::encode(derived)));
        // And the master hex must NOT appear in the line.
        assert!(!cmd.contains(&hex::encode(&master)));
    }

    #[test]
    fn enrollment_command_per_node_differs() {
        // Same master, different node_id → different enrollment line.
        // Pins that we're actually deriving per-node.
        let master = vec![0xCDu8; 32];
        let alpha = enrollment_command("h", "alpha", &master);
        let beta = enrollment_command("h", "beta", &master);
        assert_ne!(alpha, beta);
    }

    #[test]
    fn generate_control_token_is_64_hex_chars() {
        let t = generate_control_token();
        assert_eq!(t.len(), 64);
        assert!(t.chars().all(|c| c.is_ascii_hexdigit()));
    }

    #[test]
    fn generate_control_token_is_unique_each_call() {
        let a = generate_control_token();
        let b = generate_control_token();
        assert_ne!(a, b);
    }
}

#[cfg(test)]
mod scaffold_tests {
    use super::*;

    #[test]
    fn scaffold_hub_config_writes_valid_toml() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("kestrel.toml");
        let path_str = path.to_str().unwrap();
        scaffold_hub_config(path_str, "0.0.0.0:7273").unwrap();
        let contents = std::fs::read_to_string(path_str).unwrap();
        assert!(contents.contains("listen_mcp"));
        assert!(contents.contains("0.0.0.0:7273"));
        // Round-trip through HubConfig::from_str to ensure validity.
        crate::config::HubConfig::from_str(&contents).unwrap();
    }

    #[test]
    fn scaffold_hub_config_refuses_to_overwrite() {
        let dir = tempfile::tempdir().unwrap();
        let path = dir.path().join("kestrel.toml");
        let path_str = path.to_str().unwrap();
        std::fs::write(path_str, "existing").unwrap();
        let err = scaffold_hub_config(path_str, "0.0.0.0:7273").unwrap_err();
        assert!(err.to_string().contains("already exists"));
    }
}
